### ISSUE TITLE
Pinch movement angle seems wrong with `initial`

### ISSUE THREAD

**Issue by paradoxxxzero** [pmndrs/react-use-gesture#234]
I am trying to use pinch angle with the movement parameter and I get this weird behavior where the initial value seems to be taken as angle increment rather than initial value.

See this example :
https://codesandbox.io/s/angle-movement-26koh

First rotation works ok but as soon as initial angle is not zero second rotation will rotate frantically (see in console).
Pinch movement distance seems to work as intended though.

**Comment by dbismut** [comment]
Yep I think this is somehow linked to #233 (cf my comment), but thanks for making a more explicit issue. I'll work on it!

**Comment by paradoxxxzero** [comment]
FYI I temporarly worked around this with:
```js
onPinch: ({
        movement: [o, a],
        first,
        memo
      }) => {
        if (first) {
          memo = rotateZ.get()
        }
        set({ rotateZ: memo + a })
        return memo
      },
```

**Comment by dbismut** [comment]
I've just published `8.1.0-beta.3` that should fix this, can you try?

This seems to work ok now:
https://codesandbox.io/s/multi-gesture-card-rkgzi

**Comment by paradoxxxzero** [comment]
Sadly no, movement angle still doesn't work (your example uses offset): https://codesandbox.io/s/angle-movement-forked-vcn4b

**Comment by dbismut** [comment]
Ok I think I got it right this time I think. Can you please try: `8.1.0-beta.5`?
The minor drawback is that you will have to keep track of turns, until I find another solution :)

**Comment by paradoxxxzero** [comment]
Yep it works :tada:
